name: Refresh Leaderboard

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours
  workflow_dispatch:        # allow manual run

jobs:
  refresh:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install
        run: npm ci

      - name: Build snapshot
        run: npm run snapshot
        env:
          EXPLORER_API_BASE: https://hyperliquid.cloud.blockscout.com/api
          SPAZIO_CONTRACT: 0x04483D877E95Ce182e8595A3f67fDccc7B55A676
          # Optional: if you later get an API key, add it as a GitHub secret and uncomment:
          # EXPLORER_API_KEY: ${{ secrets.EXPLORER_API_KEY }}

      - name: Commit updated JSON (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add public/leaderboard.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: refresh leaderboard [skip ci]"
            git push
          fi
