name: Refresh Leaderboard (auto)

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (UTC)
  workflow_dispatch:

permissions:
  contents: write

# Prevent overlapping runs
concurrency:
  group: refresh-leaderboard
  cancel-in-progress: false

jobs:
  refresh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build snapshot
        env:
          EXPLORER_API_BASE: https://hyperliquid.cloud.blockscout.com/api
          SPAZIO_CONTRACT: 0x04483D877E95Ce182e8595A3f67fDccc7B55A676
          # Optional: add in GitHub → Settings → Secrets and variables → Actions
          EXPLORER_API_KEY: ${{ secrets.EXPLORER_API_KEY }}
        run: npm run snapshot

      - name: Commit & push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: refresh leaderboard"
          file_pattern: public/leaderboard.json

      # Trigger a Production deploy on Vercel (set the secret in GitHub)
      - name: Trigger Vercel Deploy Hook
        if: ${{ secrets.VERCEL_DEPLOY_HOOK_URL != '' }}
        run: curl -fsS -X POST "$VERCEL_DEPLOY_HOOK_URL"
        env:
          VERCEL_DEPLOY_HOOK_URL: ${{ secrets.VERCEL_DEPLOY_HOOK_URL }}
