name: Refresh Leaderboard

on:
  schedule:
    - cron: "0 */6 * * *"   # every 6 hours (UTC)
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  refresh:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    # Define env once for the whole job (quoted so YAML treats them as strings)
    env:
      EXPLORER_API_BASE: "https://hyperliquid.cloud.blockscout.com/api"
      SPAZIO_CONTRACT: "0x04483D877E95Ce182e8595A3f67fDccc7B55A676"
      # If you get an API key later, add it in repo Settings → Secrets → Actions and uncomment:
      # EXPLORER_API_KEY: ${{ secrets.EXPLORER_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps
        run: npm ci

      - name: Build snapshot
        run: npm run snapshot

      - name: Upload JSON artifact (for visibility)
        uses: actions/upload-artifact@v4
        with:
          name: leaderboard
          path: public/leaderboard.json

      - name: Create PR with updated JSON
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: refresh leaderboard"
          title: "chore: refresh leaderboard"
          body: "Automated snapshot update."
          branch: bot/refresh-leaderboard
          add-paths: |
            public/leaderboard.json
          delete-branch: true
